# Maps bet names from native site formats to prizepicks form
# Enables comparison across platforms with different naming conventions
underdog_standardized_props = {
    "Strikeouts": "Pitcher Strikeouts",
    "Fantasy Points": "Fantasy Points",
    "Hits Allowed": "Hits Allowed",
    "Hits + Runs + RBIs": "Hits+Runs+RBIs",
    "Runs": "Runs",
    "Bats + Runs + RBIs": "",
    "Total Bases": "Total Bases",
    "Batter Strikeouts": "Pitcher Strikeouts",
    "Batter Walks": "Walks Allowed",
    "Pitching Outs": "Pitching Outs",
    "Earned Runs Allowed": "Earned Runs Allowed",
    "Singles": "Singles",
    "Points": "Points",
    "Assists": "Assists",
    "Pts + Rebs + Asts": "Pts+Rebs+Asts",
    "Rebounds": "Rebounds",
    "Rebounds + Assists": "Rebs+Asts",
    "Points + Assists": "Pts+Asts",
    "Points + Rebounds": "Pts+Rebs",
    "3-Pointers Made": "3-PT Made"
}
draftkings_standardized_props = {
    "Strikeouts": "Pitcher Strikeouts",
    "Fantasy Points": "Fantasy Points",
    "Hits Allowed": "Hits Allowed",
    "Hits + Runs + RBIs": "Hits+Runs+RBIs",
    "Runs": "Runs",
    "Bats + Runs + RBIs": "",
    "Total Bases": "Total Bases",
    "Batter Strikeouts": "Pitcher Strikeouts",
    "Batter Walks": "Walks Allowed",
    "Pitching Outs": "Pitching Outs",
    "Earned Runs Allowed": "Earned Runs Allowed",
    "Singles": "Singles",
    "Home Runs": "Home Runs",
    "Hits": "Hits",
    "RBIs": "RBIs",
    "Singles": "Singles",
    "Doubles": "Doubles",
    "Walks": "Walks",
    "Runs Scored": "Runs Scored",
    "Strikeouts Thrown": "Pitcher Strikeouts",
    "Walks Allowed": "Walks Allowed",
    "Outs Recorded": "Pitching Outs",
    "Points": "Points",
    "Rebounds": "Rebounds",
    "Threes": "3-PT Made",
    "Assists": "Assists",
}
fanduel_standardized_props = {
    "Points": "Points",
    "Assists": "Assists",
    "Pts + Reb + Ast": "Pts+Rebs+Asts",
    "Rebounds": "Rebounds",
    "Reb + Ast": "Rebs+Asts",
    "Pts + Ast": "Pts+Asts",
    "Pts + Reb": "Pts+Rebs",
    "Made Threes": "3-PT Made",
    "Strikeouts": "Pitcher Strikeouts",
    "Outs Recorded": "Pitching Outs"
}